spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

cors:
  origins: http://localhost:5173,http://localhost:3000

server:
  servlet:
    context-path: /escola/api

springdoc:
  swagger-ui:
    path: /public/swagger